# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_course', models.CharField(max_length=4)),
                ('book_sem', models.CharField(max_length=1)),
                ('book_sub', models.CharField(max_length=100)),
                ('book_price', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Pno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pno', models.CharField(max_length=11)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sell.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
    ]
